[package]
name = "example_lightning"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wrflib = { path="../../main" }
wrflib_components = { path="../../components" }

[features]
disable-interaction=["wrflib/disable-fonts"]
