# Copyright (c) 2021-present, Cruise LLC
#
# This source code is licensed under the Apache License, Version 2.0,
# found in the LICENSE-APACHE file in the root directory of this source tree.
# You may not use this file except in compliance with the License.

name: Rust

on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Update package list
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install libegl1-mesa-dev libxcursor-dev
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Build
      run: cargo build -p bigedit --verbose
    - name: Run tests
      run: cargo test -p bigedit --verbose
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Build
      run: |
        source $HOME/.cargo/env
        cargo build -p bigedit --verbose
    - name: Run tests
      run: |
        source $HOME/.cargo/env
        cargo test -p bigedit --verbose
